### PR TITLE
Switch to dark mode, update tag line

### PR DESCRIPTION
**Pull request by jredbeard**
## Brief description
This switches to dark mode by using the built in dark mode part of the existing theme but with some small changes. It also updates the tag line and changes the buttons to a gradient instead of a flat color. The logo has also been added to the hero.

### CODE REVIEW

**Comment by sgerbino** [comment]
Everything looks great here except for the token supply... it's atrocious -- can we get a replacement for that before merging this?

image

**Comment by jredbeard** [comment]
> Everything looks great here except for the token supply... it's atrocious -- can we get a replacement for that before merging this?

@sgerbino yeah - any idea who did that image? it was shared on social media a long time ago... maybe Frank? It would be cool to get one with a transparent background and have the text changed to white (might be nice to get both versions like that actually). We could use an NPM package to generate a pie chart in real time, but I don't know of any packages that do 3d ones like that with the shadow beneath it so it wouldn't look quite as good

**Comment by sgerbino** [comment]
I just noticed the sticker header image needs to be replaced, maybe just white?

image

**Comment by jredbeard** [comment]
> I just noticed the sticker header image needs to be replaced, maybe just white?

Ok @sgerbino, updated tokenomics image and now it switches to a white logo after it's scrolled on top of the smokey navbar. I also set a max width on the hero header image so that it doesn't stretch too much.

image

**Comment by sgerbino** [comment]
This looks beautiful, thank you. You are a gentleman and a scholar.

**Review by sgerbino — APPROVED** [review]

**Pull request merged**
