### PR TITLE
Background that matches the slate of the documentation site

### PR DESCRIPTION
**Pull request by sgerbino**
## Brief description
This changes the background color of the site to match that of the documentation site, adjusts the hero image and mobile image accordingly (I think). Putting up a PR to have a look.

### CODE REVIEW

**Comment by sgerbino** [comment]
Probably could make the lighter boxes match the lighter slate color of the documentation site...

**Comment by mvandeberg** [comment]
This has the background of the site match the header of docs site. If the purpose of this PR is to make those sites feel more continuous, I don't think this change achieves it because the background colors are still changing. Granted, I am not a designed, but it isn't working for me.

**Comment by sgerbino** [comment]
> This has the background of the site match the header of docs site. If the purpose of this PR is to make those sites feel more continuous, I don't think this change achieves it because the background colors are still changing. Granted, I am not a designer, but it isn't working for me.

It's at least using the same colors. I think the site looks better on the darker background and using the lighter one as a highlight would probably make them feel more connected.

**Comment by sgerbino** [comment]
WIP: Trying to have a clever way to use `#1e2129` as box highlight color in dark mode

**Comment by jredbeard** [comment]
> WIP: Trying to have a clever way to use `#1e2129` as box highlight color in dark mode

oh ok - which boxes?

**Comment by sgerbino** [comment]
> > WIP: Trying to have a clever way to use `#1e2129` as box highlight color in dark mode
> 
> oh ok - which boxes?

All these secondary colors is what I was thinking
image
image
image

**Comment by sgerbino** [comment]
For some reason the Whitepaper page has a completely different background

**Comment by sgerbino** [comment]
Karlos made a new favicon, I think it looks MUCH better

**Comment by jredbeard** [comment]
> Karlos made a new favicon, I think it looks MUCH better

Awesome! if you want, you can just use a PNG now. Even for a die hard compatibility snob like me, if someone is using a browser that is 15 years old and can't support it, they can just not see the favicon. It's totally fine.

**Comment by jredbeard** [comment]
> For some reason the Whitepaper page has a completely different background, also the menu dropdown.

Thie whitepaper page looks to have the same new slate background to me.... at least locally in a build it does anyway. I checked the chrome inspector and it shows the correct background color on the body after navigating to the whitepaper.

**Comment by jredbeard** [comment]
> > For some reason the Whitepaper page has a completely different background, also the menu dropdown.
> 
> Thie whitepaper page looks to have the same new slate background to me.... at least locally in a build it does anyway. I checked the chrome inspector and it shows the correct background color on the body after navigating to the whitepaper.

@sgerbino I take this comment back lol. You have a better eye than me. I think I see the problem

**Comment by jredbeard** [comment]
> @sgerbino I take this comment back lol. You have a better eye than me. I think I see the problem
fixed: https://github.com/koinos/koinos-io-website/pull/53

**Review by mvandeberg — APPROVED** [review]

**Pull request merged**
